CONTIKI = ../../../../lib/contiki
SENSORNET = ../../..

# test parameters
TTL = 180

# load piloty1 positions
include $(SENSORNET)/test/testbed/piloty1.defines

__GRAPH_DEBUG__=1
__NEIGHBOR_DISCOVERY_DEBUG__=1
__BROADCAST_DEBUG__=1
__SERIALIZE_DEBUG__=1

include $(SENSORNET)/Makefile.include
include $(CONTIKI)/Makefile.include
