language: c

before_install:
  - git submodule update --init --recursive

before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update

  ## Install msp430 toolchain
  - sudo apt-get -qq install lib32z1
  - $WGET http://adamdunkels.github.io/contiki-fork/mspgcc-4.7.0-compiled.tar.bz2 &&
    tar xjf mspgcc*.tar.bz2 -C /tmp/ &&
    sudo cp -f -r /tmp/msp430/* /usr/local/ &&
    rm -rf /tmp/msp430 mspgcc*.tar.bz2 &&
    msp430-gcc --version
  
script:
  ## Build code
  - make -C src/

  ## Build and run unit tests
  - make -C src/test run-unittests
  
  ## Build and run Cooja test
  - make -C src/test/cooja/broadcast-with-checksum run-unittest
  - make -C src/test/cooja/2-hop-test run-unittest
  - make -C src/test/cooja/2-hop-test-50percent-drop run-unittest
  - make -C src/test/cooja/3-hop-test run-unittest
  - make -C src/test/cooja/3-hop-test-50percent-drop run-unittest
  - make -C src/test/cooja/routing run-unittest
  - make -C src/test/cooja/routing-50percent-drop run-unittest
  - make -C src/test/cooja/2-hop-test-low-ttl run-unittest
  - make -C src/test/cooja/2-hop-test-dying-node run-unittest
